name: organizer
description: Seminary organizer tool made in Flutter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firestore_ui: ^1.24.0
  pdf: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/
    - assets/files/

  # example:
  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/open-sans.ttf