// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBgWYm9zV19OZW1p-hEEL3SO7lrU1EXEfY",
      authDomain: "fsspolgs.firebaseapp.com",
      projectId: "fsspolgs",
      storageBucket: "fsspolgs.appspot.com",
      messagingSenderId: "530829375587",
      appId: "1:530829375587:web:2ecad72e15abc0ae73a056",
      measurementId: "G-58DS08W2V6");
}
